
- name: "Promote CV/CCVs to Selected Environments"
  redhat.satellite.content_view_version:
    validate_certs: "{{ satellite_validate_ssl }}"
    username: "{{ satellite_server_user }}"
    password: "{{ satellite_server_password }}"
    server_url: "{{ satellite_server_url }}"
    content_view: "{{ item }}"
    organization: "{{ satellite_server_organization }}"
    current_lifecycle_environment: "{{ currentenv }}"
    lifecycle_environments: "{{ envs }}"
  with_items: "{{ cvs }}"  
